name: update

on:
  push:
    branches:
      - main

jobs:
  update:
    name: Pulumi Update
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: recursive

      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: taehoio-global
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
        with:
          pulumi-version: 3.23.2

      - name: Download go mod dependencies
        run: go mod download

      - name: Preview global project
        uses: pulumi/actions@v3
        with:
          command: preview
          comment-on-pr: true
          stack-name: global
          work-dir: ./global/
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Preview staging project
        uses: pulumi/actions@v3
        with:
          command: preview
          comment-on-pr: true
          stack-name: staging
          work-dir: ./staging/
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Update global project
        uses: pulumi/actions@v3
        with:
          command: up
          comment-on-pr: true
          stack-name: global
          work-dir: ./global/
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Update staging project
        uses: pulumi/actions@v3
        with:
          command: up
          comment-on-pr: true
          stack-name: staging
          work-dir: ./staging/
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Update production project
        uses: pulumi/actions@v3
        with:
          command: up
          comment-on-pr: true
          stack-name: production
          work-dir: ./production/
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
